"""add tradingview dex symbol cache columns

Revision ID: 107eaa35737d
Revises: b95e32664875
Create Date: 2026-09-26 14:45:56.173101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '107eaa35737d'
down_revision: Union[str, Sequence[str], None] = 'b95e32664875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tradingview_dex_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('tradingview_dex_symbol_checked_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.drop_column('tradingview_dex_symbol_checked_at')
        batch_op.drop_column('tradingview_dex_symbol')

    # ### end Alembic commands ###
