"""add coin url fields

Revision ID: 1f6025b958aa
Revises: 591a64f53113
Create Date: 2026-09-24 21:07:28.373887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1f6025b958aa'
down_revision: Union[str, Sequence[str], None] = '591a64f53113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('whitepaper_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('telegram_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('source_code_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('explorer_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.drop_column('explorer_url')
        batch_op.drop_column('source_code_url')
        batch_op.drop_column('telegram_url')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('whitepaper_url')
        batch_op.drop_column('website_url')

    # ### end Alembic commands ###
