"""add defillama unlocks slug cache columns

Revision ID: 331e706fd5c9
Revises: 107eaa35737d
Create Date: 2026-09-29 13:27:25.837577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '331e706fd5c9'
down_revision: Union[str, Sequence[str], None] = '107eaa35737d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defillama_unlocks_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('defillama_unlocks_checked_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.drop_column('defillama_unlocks_checked_at')
        batch_op.drop_column('defillama_unlocks_slug')

    # ### end Alembic commands ###
