"""add is_primary to coin_contract

Revision ID: 591a64f53113
Revises: 85b94071e399
Create Date: 2026-09-23 01:20:44.339646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '591a64f53113'
down_revision: Union[str, Sequence[str], None] = '85b94071e399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'coin_contract',
        sa.Column('is_primary', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin_contract', 'is_primary')
    # ### end Alembic commands ###
