"""create coin and category tables

Revision ID: 7234e6f2c331
Revises: 
Create Date: 2026-09-21 02:52:55.820031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7234e6f2c331'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cmc_category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_cmc_category_id'), 'category', ['cmc_category_id'], unique=True)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=False)
    op.create_table('coin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cmc_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cmc_rank', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('volume_24h_usd', sa.Float(), nullable=True),
    sa.Column('percent_change_1h', sa.Float(), nullable=True),
    sa.Column('percent_change_24h', sa.Float(), nullable=True),
    sa.Column('percent_change_7d', sa.Float(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_cmc_id'), 'coin', ['cmc_id'], unique=True)
    op.create_index(op.f('ix_coin_slug'), 'coin', ['slug'], unique=True)
    op.create_index(op.f('ix_coin_symbol'), 'coin', ['symbol'], unique=False)
    op.create_table('coin_category',
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], ),
    sa.PrimaryKeyConstraint('coin_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coin_category')
    op.drop_index(op.f('ix_coin_symbol'), table_name='coin')
    op.drop_index(op.f('ix_coin_slug'), table_name='coin')
    op.drop_index(op.f('ix_coin_cmc_id'), table_name='coin')
    op.drop_table('coin')
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_cmc_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
