"""add supply/FDV fields and reddit/facebook urls

Revision ID: 81adaaf1e342
Revises: 1f6025b958aa
Create Date: 2026-09-24 21:30:47.345205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '81adaaf1e342'
down_revision: Union[str, Sequence[str], None] = '1f6025b958aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('circulating_supply', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_supply', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_supply', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fully_diluted_market_cap', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reddit_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('reddit_url')
        batch_op.drop_column('fully_diluted_market_cap')
        batch_op.drop_column('max_supply')
        batch_op.drop_column('total_supply')
        batch_op.drop_column('circulating_supply')

    # ### end Alembic commands ###
