"""add coin_contract table

Revision ID: 85b94071e399
Revises: d1d7fb970874
Create Date: 2026-09-23 01:11:37.423785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '85b94071e399'
down_revision: Union[str, Sequence[str], None] = 'd1d7fb970874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contract_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_contract_coin_id'), 'coin_contract', ['coin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_contract_coin_id'), table_name='coin_contract')
    op.drop_table('coin_contract')
    # ### end Alembic commands ###
