"""add x_username cached_tweets last_social_update to coin

Revision ID: 8ae1beb6e998
Revises: 81adaaf1e342
Create Date: 2026-09-25 13:11:29.996225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8ae1beb6e998'
down_revision: Union[str, Sequence[str], None] = '81adaaf1e342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('cached_tweets', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_social_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.drop_column('last_social_update')
        batch_op.drop_column('cached_tweets')
        batch_op.drop_column('x_username')

    # ### end Alembic commands ###
