"""add sparkline_7d to coin

Revision ID: 9e229113a9a0
Revises: 7234e6f2c331
Create Date: 2026-09-22 23:22:17.400128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e229113a9a0'
down_revision: Union[str, Sequence[str], None] = '7234e6f2c331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin', sa.Column('sparkline_7d', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin', 'sparkline_7d')
    # ### end Alembic commands ###
