"""add business_model_category and market_pairs to coin

Revision ID: b95e32664875
Revises: 0aad65903a47
Create Date: 2026-09-25 20:05:19.231315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b95e32664875'
down_revision: Union[str, Sequence[str], None] = '0aad65903a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_model_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('cached_market_pairs', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('market_pairs_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.drop_column('market_pairs_updated_at')
        batch_op.drop_column('cached_market_pairs')
        batch_op.drop_column('business_model_category')

    # ### end Alembic commands ###
