"""drop sparkline_7d from coin

Revision ID: d1d7fb970874
Revises: 9e229113a9a0
Create Date: 2026-09-22 23:47:28.123422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1d7fb970874'
down_revision: Union[str, Sequence[str], None] = '9e229113a9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin', 'sparkline_7d')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin', sa.Column('sparkline_7d', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
