"""add peer_group to coin

Revision ID: dc7274dded9a
Revises: 331e706fd5c9
Create Date: 2026-10-05 00:23:50.074065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dc7274dded9a'
down_revision: Union[str, Sequence[str], None] = '331e706fd5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peer_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.drop_column('peer_group')

    # ### end Alembic commands ###
