"""add business_model_category and market_pairs to coins

Revision ID: 1d410dd73744
Revises: 8369bbae1384
Create Date: 2026-09-25 20:05:11.099098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d410dd73744'
down_revision: Union[str, None] = '8369bbae1384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('business_model_category', sa.String(length=150), nullable=True))
    op.add_column('coins', sa.Column('cached_market_pairs', sa.JSON(), nullable=True))
    op.add_column('coins', sa.Column('market_pairs_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'market_pairs_updated_at')
    op.drop_column('coins', 'cached_market_pairs')
    op.drop_column('coins', 'business_model_category')
    # ### end Alembic commands ###
