"""add description_synced_at to coins

Revision ID: 3bf17bd88ea2
Revises: 5ee5d3c9dba0
Create Date: 2026-09-25 16:35:46.328933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf17bd88ea2'
down_revision: Union[str, None] = '5ee5d3c9dba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('description_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'description_synced_at')
    # ### end Alembic commands ###
