"""add coin url fields (website, whitepaper, socials, explorer)

Revision ID: 4783bee88bc5
Revises: 9fbab21ed2d3
Create Date: 2026-09-24 21:07:01.350645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4783bee88bc5'
down_revision: Union[str, None] = '9fbab21ed2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('website_url', sa.String(length=500), nullable=True))
    op.add_column('coins', sa.Column('whitepaper_url', sa.String(length=500), nullable=True))
    op.add_column('coins', sa.Column('twitter_url', sa.String(length=500), nullable=True))
    op.add_column('coins', sa.Column('telegram_url', sa.String(length=500), nullable=True))
    op.add_column('coins', sa.Column('source_code_url', sa.String(length=500), nullable=True))
    op.add_column('coins', sa.Column('explorer_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'explorer_url')
    op.drop_column('coins', 'source_code_url')
    op.drop_column('coins', 'telegram_url')
    op.drop_column('coins', 'twitter_url')
    op.drop_column('coins', 'whitepaper_url')
    op.drop_column('coins', 'website_url')
    # ### end Alembic commands ###
