"""widen supply/FDV column precision

Revision ID: 4fc23fc53fc5
Revises: eefcf633fdbe
Create Date: 2026-09-24 21:35:56.044606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc23fc53fc5'
down_revision: Union[str, None] = 'eefcf633fdbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coins', 'circulating_supply',
               existing_type=sa.NUMERIC(precision=30, scale=2),
               type_=sa.Numeric(precision=36, scale=2),
               existing_nullable=True)
    op.alter_column('coins', 'total_supply',
               existing_type=sa.NUMERIC(precision=30, scale=2),
               type_=sa.Numeric(precision=36, scale=2),
               existing_nullable=True)
    op.alter_column('coins', 'max_supply',
               existing_type=sa.NUMERIC(precision=30, scale=2),
               type_=sa.Numeric(precision=36, scale=2),
               existing_nullable=True)
    op.alter_column('coins', 'fully_diluted_market_cap',
               existing_type=sa.NUMERIC(precision=24, scale=2),
               type_=sa.Numeric(precision=36, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coins', 'fully_diluted_market_cap',
               existing_type=sa.Numeric(precision=36, scale=2),
               type_=sa.NUMERIC(precision=24, scale=2),
               existing_nullable=True)
    op.alter_column('coins', 'max_supply',
               existing_type=sa.Numeric(precision=36, scale=2),
               type_=sa.NUMERIC(precision=30, scale=2),
               existing_nullable=True)
    op.alter_column('coins', 'total_supply',
               existing_type=sa.Numeric(precision=36, scale=2),
               type_=sa.NUMERIC(precision=30, scale=2),
               existing_nullable=True)
    op.alter_column('coins', 'circulating_supply',
               existing_type=sa.Numeric(precision=36, scale=2),
               type_=sa.NUMERIC(precision=30, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
