"""add description to coins

Revision ID: 5ee5d3c9dba0
Revises: 8083ca7caf4a
Create Date: 2026-09-25 15:29:46.567845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee5d3c9dba0'
down_revision: Union[str, None] = '8083ca7caf4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'description')
    # ### end Alembic commands ###
