"""add tradingview dex symbol cache columns

Revision ID: 70a7887a42ae
Revises: b1d0fd86c529
Create Date: 2026-09-26 14:40:12.777594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a7887a42ae'
down_revision: Union[str, None] = 'b1d0fd86c529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('tradingview_dex_symbol', sa.String(length=120), nullable=True))
    op.add_column('coins', sa.Column('tradingview_dex_symbol_checked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'tradingview_dex_symbol_checked_at')
    op.drop_column('coins', 'tradingview_dex_symbol')
    # ### end Alembic commands ###
