"""add x_username cached_tweets last_social_update to coins

Revision ID: 8083ca7caf4a
Revises: 4fc23fc53fc5
Create Date: 2026-09-25 13:10:16.140816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8083ca7caf4a'
down_revision: Union[str, None] = '4fc23fc53fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('x_username', sa.String(length=50), nullable=True))
    op.add_column('coins', sa.Column('cached_tweets', sa.JSON(), nullable=True))
    op.add_column('coins', sa.Column('last_social_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'last_social_update')
    op.drop_column('coins', 'cached_tweets')
    op.drop_column('coins', 'x_username')
    # ### end Alembic commands ###
