"""add business_summary_model to coins

Revision ID: 8369bbae1384
Revises: c8e4abcb8dfe
Create Date: 2026-09-25 19:23:42.208246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8369bbae1384'
down_revision: Union[str, None] = 'c8e4abcb8dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('business_summary_model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'business_summary_model')
    # ### end Alembic commands ###
