"""add percent_change_1h and percent_change_7d to coins

Revision ID: 97c7f6746aae
Revises: 7a60072c6b2f
Create Date: 2026-09-21 02:34:40.830234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c7f6746aae'
down_revision: Union[str, None] = '7a60072c6b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('percent_change_1h', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('coins', sa.Column('percent_change_7d', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'percent_change_7d')
    op.drop_column('coins', 'percent_change_1h')
    # ### end Alembic commands ###
