"""add coin_contracts table and contracts sync type

Revision ID: 9fcdd26250f2
Revises: 97c7f6746aae
Create Date: 2026-09-23 01:10:34.233460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fcdd26250f2'
down_revision: Union[str, None] = '97c7f6746aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # New SyncType.CONTRACTS enum value — ADD VALUE can't run inside the
    # migration's normal transaction on Postgres, so it needs its own
    # autocommit block.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE synctype ADD VALUE IF NOT EXISTS 'CONTRACTS'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=255), nullable=False),
    sa.Column('platform_symbol', sa.String(length=32), nullable=True),
    sa.Column('contract_address', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_contracts_coin_id'), 'coin_contracts', ['coin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_contracts_coin_id'), table_name='coin_contracts')
    op.drop_table('coin_contracts')
    # ### end Alembic commands ###
