"""add description_ai_generated_at to coins

Revision ID: b1d0fd86c529
Revises: 1d410dd73744
Create Date: 2026-09-26 01:55:42.656411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d0fd86c529'
down_revision: Union[str, None] = '1d410dd73744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('description_ai_generated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'description_ai_generated_at')
    # ### end Alembic commands ###
