"""add business_summary to coins

Revision ID: c8e4abcb8dfe
Revises: 3bf17bd88ea2
Create Date: 2026-09-25 18:34:03.089126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e4abcb8dfe'
down_revision: Union[str, None] = '3bf17bd88ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('business_summary', sa.Text(), nullable=True))
    op.add_column('coins', sa.Column('business_summary_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'business_summary_updated_at')
    op.drop_column('coins', 'business_summary')
    # ### end Alembic commands ###
