"""create coins, categories, sync_logs tables

Revision ID: d515684b25a8
Revises: 
Create Date: 2026-09-21 01:17:59.489451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd515684b25a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cmc_category_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_cmc_category_id'), 'categories', ['cmc_category_id'], unique=True)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cmc_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('cmc_rank', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('market_cap_usd', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('volume_24h_usd', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('percent_change_24h', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coins_cmc_id'), 'coins', ['cmc_id'], unique=True)
    op.create_index(op.f('ix_coins_slug'), 'coins', ['slug'], unique=True)
    op.create_index(op.f('ix_coins_symbol'), 'coins', ['symbol'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.Enum('LISTINGS', 'CATEGORIES', name='synctype'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'RUNNING', name='syncstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coin_category',
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coin_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coin_category')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_coins_symbol'), table_name='coins')
    op.drop_index(op.f('ix_coins_slug'), table_name='coins')
    op.drop_index(op.f('ix_coins_cmc_id'), table_name='coins')
    op.drop_table('coins')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_cmc_category_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
