"""add defillama unlocks slug cache columns

Revision ID: ee0b064b67d3
Revises: 70a7887a42ae
Create Date: 2026-09-29 13:26:54.657337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0b064b67d3'
down_revision: Union[str, None] = '70a7887a42ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('defillama_unlocks_slug', sa.String(length=120), nullable=True))
    op.add_column('coins', sa.Column('defillama_unlocks_checked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'defillama_unlocks_checked_at')
    op.drop_column('coins', 'defillama_unlocks_slug')
    # ### end Alembic commands ###
