"""add supply/FDV fields and reddit/facebook urls

Revision ID: eefcf633fdbe
Revises: 4783bee88bc5
Create Date: 2026-09-24 21:30:23.024974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eefcf633fdbe'
down_revision: Union[str, None] = '4783bee88bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('circulating_supply', sa.Numeric(precision=30, scale=2), nullable=True))
    op.add_column('coins', sa.Column('total_supply', sa.Numeric(precision=30, scale=2), nullable=True))
    op.add_column('coins', sa.Column('max_supply', sa.Numeric(precision=30, scale=2), nullable=True))
    op.add_column('coins', sa.Column('fully_diluted_market_cap', sa.Numeric(precision=24, scale=2), nullable=True))
    op.add_column('coins', sa.Column('reddit_url', sa.String(length=500), nullable=True))
    op.add_column('coins', sa.Column('facebook_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'facebook_url')
    op.drop_column('coins', 'reddit_url')
    op.drop_column('coins', 'fully_diluted_market_cap')
    op.drop_column('coins', 'max_supply')
    op.drop_column('coins', 'total_supply')
    op.drop_column('coins', 'circulating_supply')
    # ### end Alembic commands ###
