"""add is_primary to coin_contracts

Revision ID: fbe2103efbc2
Revises: 9fcdd26250f2
Create Date: 2026-09-23 01:20:35.686276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe2103efbc2'
down_revision: Union[str, None] = '9fcdd26250f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'coin_contracts',
        sa.Column('is_primary', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('coin_contracts', 'is_primary', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin_contracts', 'is_primary')
    # ### end Alembic commands ###
