"""Local storage model for cached CoinMarketCap coin listings."""

from datetime import datetime

from sqlalchemy import JSON, Column
from sqlmodel import Field, Relationship, SQLModel

from frontend.models.category import Category, CoinCategoryLink
from frontend.models.coin_contract import CoinContract


class Coin(SQLModel, table=True):
    __tablename__ = "coin"

    id: int | None = Field(default=None, primary_key=True)
    cmc_id: int = Field(index=True, unique=True)
    symbol: str = Field(index=True)
    name: str
    slug: str = Field(index=True, unique=True)
    cmc_rank: int | None = None

    price_usd: float | None = None
    market_cap_usd: float | None = None
    volume_24h_usd: float | None = None
    percent_change_1h: float | None = None
    percent_change_24h: float | None = None
    percent_change_7d: float | None = None

    circulating_supply: float | None = None
    total_supply: float | None = None
    max_supply: float | None = None
    fully_diluted_market_cap: float | None = None

    # Mirrored from the app/ backend's own Coin.* url fields (sourced from
    # CMC's /v2/cryptocurrency/info `urls` object) via reflex_cache_service.
    website_url: str | None = None
    whitepaper_url: str | None = None
    twitter_url: str | None = None
    telegram_url: str | None = None
    source_code_url: str | None = None
    explorer_url: str | None = None
    reddit_url: str | None = None
    facebook_url: str | None = None
    description: str | None = None
    # Mirrored from app/services/business_summary_service.py's on-demand
    # AI-generated "what does this coin do / how does it make money"
    # explainer (see coin_detail.py's _business_summary_section).
    business_summary: str | None = None
    # The exact OpenRouter model slug that generated business_summary (see
    # app/services/business_summary_service.py) — drives coin_detail.py's
    # "Generated by AI · <model>" attribution badge.
    business_summary_model: str | None = None
    # Mirrored from app/services/business_summary_service.py's CATEGORY:
    # line — a short, AI-generated business-model classification more
    # specific than the broad CMC narrative tags (see coin_detail.py's
    # glowing category badge next to the live-chart heading).
    business_model_category: str | None = None

    # Mirrored from app/services/market_pairs_service.py's on-demand CEX/
    # DEX market-pair cache — top-10-CEX + top-10-DEX already-normalized
    # {exchange_name, exchange_icon_url, market_pair, is_dex, price,
    # volume_24h, volume_pct, last_updated_display} dicts (see
    # coin_detail.py's Markets section).
    cached_market_pairs: list | None = Field(default=None, sa_column=Column(JSON))
    market_pairs_updated_at: datetime | None = None

    # Mirrored from app/services/tradingview_symbol_service.py's last-resort
    # TradingView chart-symbol lookup for a coin with zero real CEX pairs
    # (see coin_state.py's CoinState.refresh_tradingview_dex_symbol /
    # _resolve_tradingview_symbol).
    tradingview_dex_symbol: str | None = None
    tradingview_dex_symbol_checked_at: datetime | None = None

    # Mirrors the app/ backend's dormant X-post cache columns (see
    # app/models/coin.py — the scraping backend that used to populate
    # these was removed per explicit request). cached_tweets is a plain
    # JSON column (SQLite has no JSONB); kept, not dropped, in case a
    # scraping backend is added back later.
    x_username: str | None = None
    cached_tweets: list | None = Field(default=None, sa_column=Column(JSON))
    last_social_update: datetime | None = None

    last_synced_at: datetime | None = None

    categories: list[Category] = Relationship(
        back_populates="coins", link_model=CoinCategoryLink
    )
    contracts: list[CoinContract] = Relationship(back_populates="coin")
